loki:
  schemaConfig:
    configs:
      - from: "2024-04-01"
        store: tsdb
        object_store: s3
        schema: v13
        index:
          prefix: loki_index_
          period: 24h
  storage_config:
    aws:
      region: ap-northeast-2
      bucketnames: sbk-sp-dev-core-loki-bucket
      s3forcepathstyle: false
  pattern_ingester:
      enabled: true
  auth_enabled: false
  limits_config:
    allow_structured_metadata: true
    volume_enabled: true
    retention_period: 72h # 3 days retention
  querier:
    max_concurrent: 4

  storage:
    type: s3
    bucketNames:
        chunks: sbk-sp-dev-core-loki-chunk-bucket
        ruler: sbk-sp-dev-core-loki-ruler-bucket
        admin: sbk-sp-dev-core-loki-admin-bucket
        # admin: sbk-sp-dev-core-loki-admin-bucket
    s3:
      # s3 URL can be used to specify the endpoint, access key, secret key, and bucket name this works well for S3 compatible storages or if you are hosting Loki on-premises and want to use S3 as the storage backend. Either use the s3 URL or the individual fields below (AWS endpoint, region, secret).
      # s3: s3://access_key:secret_access_key@custom_endpoint/bucket_name
      # AWS endpoint URL
      # endpoint: <your-endpoint>
      # AWS region where the S3 bucket is located
      region: ap-northeast-2
      # AWS secret access key
      # secretAccessKey: <your-secret-access-key>
      # AWS access key ID
      # accessKeyId: <your-access-key-id>
      # AWS signature version (e.g., v2 or v4)
      signatureVersion: v4
      # Forces the path style for S3 (true/false)
      s3ForcePathStyle: false
      # Allows insecure (HTTP) connections (true/false)
      insecure: false
      # HTTP configuration settings
      http_config: {}

deploymentMode: SimpleScalable

backend:
  replicas: 3
  persistence:
    enabled: true
    storageClass: "gp2"
    size: 10Gi
read:
  replicas: 3
  persistence:
    enabled: true
    storageClass: "gp2"
    size: 10Gi
write:
  replicas: 3
  persistence:
    enabled: true
    storageClass: "gp2"
    size: 10Gi

# Disable minio storage
minio:
  enabled: false